export const LISTINGS_ERRORED = 'LISTINGS_ERRORED';
export const LISTINGS_IS_LOADING = 'LISTINGS_IS_LOADING';
export const LISTINGS_FETCH_SUCCESS = 'LISTINGS_FETCH_SUCCESS';

export const LISTING_DELETING_ERRORED = 'LISTING_DELETING_ERRORED';
export const LISTING_IS_DELETING = 'LISTING_IS_DELETING';
export const LISTING_DELETED = 'LISTING_DELETED';

export const LISTING_UPDATE_ERRORED = 'LISTING_UPDATE_ERRORED';
export const LISTING_IS_UPDATING = 'LISTING_IS_UPDATING';
export const LISTING_UPDATED = 'LISTING_UPDATED';

